import { Heading, Text, chakra, Box, Button } from '@chakra-ui/react';
import Head from 'next/head';
import bgSec1 from '@/assets/images/bg-sec-1.png';
import { LogoIcon } from '@/assets/icons/LogoIcon';
import { ButtonDefault } from '@/components/common/ButtonDefault';
export const Home: React.FC = () => {
  return (
    <>
      <Head>
        <title>S-30</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <chakra.main>
        <chakra.section
          className="animate__animated animate__fadeIn animate__slower 1s"
          sx={{
            h: { base: '100vh' },
            w: { base: '100%' },

            bg: { base: 'none', xl: `url(${bgSec1.src}) no-repeat` },
            bgPosition: { base: 'none', xl: 'center' },
            bgSize: { base: 'none', xl: 'cover' },
            pos: 'relative',
          }}
        >
          <Box
            w={{ base: '100vw', lg: '30vw', xl: '30vw' }}
            maxW="31remrem"
            h={{ base: '10rem' }}
            pos="absolute"
            inset={{ base: '0 auto', lg: '5rem 0 auto 15rem', xl: '5rem 0 auto 15rem' }}
            className="animate__animated animate__fadeInLeft"
            px={{
              lg: '0',
              xl: '0',
              base: '1rem',
            }}
          >
            <LogoIcon
              h={{ base: '10rem', lg: '10rem', xl: '10rem' }}
              w={{
                lg: '15rem',
                xl: '15rem',
                base: '20rem',
              }}
            />
            <Heading as="h3" fontSize="1rem" lineHeight="1.7rem" mt="1rem" textAlign="left">
              ACELERE O SEU METABOLISMO E CONSIGA DIMINUIR QUILOS NA BALANÇA COM O{' '}
              <chakra.span color="blue.500">S30</chakra.span>, SÃO 30 DIAS DE TREINOS COM DURAÇÃO DE
              NO MÁXIMO 12 MINUTOS QUE FARÃO COM QUE O SEU CORPO{' '}
              <chakra.span color="blue.500">QUEIME 3X MAIS CALORIAS QUE O NORMAL</chakra.span>
            </Heading>
            <ButtonDefault />
          </Box>
        </chakra.section>
      </chakra.main>

      <chakra.footer bg="blue.500" w="100%" textAlign="center" p="1rem">
        <Text>Copyright © 2022 Nome da Empresa de Leo</Text>
      </chakra.footer>
    </>
  );
};
